name: Build App

on:
  workflow_dispatch:
    inputs:
      build_configuration:
        description: Build Configuration
        required: false
        type: string
        default: Release
      upload_artifact:
        description: Upload artifact
        required: false
        type: boolean
        default: true
  workflow_call:
    inputs:
      build_configuration:
        required: false
        type: string
        default: Release
      upload_artifact:
        required: false
        type: boolean
        default: true
    secrets:
      CURSE_FORGE_API_KEY:
        required: false
      MACOS_CERTIFICATE:
        required: false
      MACOS_CERTIFICATE_PASSWORD:
        required: false
      MACOS_SIGNING_IDENTITY:
        required: false
      MACOS_SIGNING_TEAM:
        required: false

jobs:
  build:
    runs-on: macos-26
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Set version
        run: echo "BUILD_NUMBER=$(git rev-list --count HEAD)" >> $GITHUB_ENV

      - name: Generate Secrets.properties
        run: |
          cat > ./Resources/Secrets.properties <<'EOF'
          CURSE_FORGE_API_KEY=${{ secrets.CURSE_FORGE_API_KEY }}
          EOF

      - name: Import codesign cert
        if: ${{ inputs.build_configuration == 'Release' }}
        uses: apple-actions/import-codesign-certs@v7
        with:
          p12-file-base64: ${{ secrets.MACOS_CERTIFICATE }}
          p12-password: ${{ secrets.MACOS_CERTIFICATE_PASSWORD }}

      - name: Build app
        run: |
          echo "Build number: $BUILD_NUMBER"
          COMMON_ARGS=(
            -project PCL.Mac.xcodeproj
            -scheme PCL.Mac
            -configuration "${{ inputs.build_configuration }}"
            CURRENT_PROJECT_VERSION=$BUILD_NUMBER
            -archivePath build
          )

          if [ "${{ inputs.build_configuration }}" = "Release" ]; then
            xcodebuild archive \
              "${COMMON_ARGS[@]}" \
              CODE_SIGN_STYLE=Manual \
              CODE_SIGN_IDENTITY="${{ secrets.MACOS_SIGNING_IDENTITY }}" \
              DEVELOPMENT_TEAM="${{ secrets.MACOS_SIGNING_TEAM }}" \
              ENABLE_HARDENED_RUNTIME=YES
          else
            xcodebuild archive \
              "${COMMON_ARGS[@]}"
          fi

      - name: Prepare app artifact
        run: |
          mkdir "PCL.Mac-artifact"
          ditto ./build.xcarchive/Products/Applications/PCL.Mac.app ./PCL.Mac-artifact/PCL.Mac.app
          ditto ./build.xcarchive ./PCL.Mac-artifact/build.xcarchive
          ditto -c -k --sequesterRsrc ./PCL.Mac-artifact ./PCL.Mac-artifact.zip

      - name: Upload app artifact
        if: ${{ inputs.upload_artifact }}
        uses: actions/upload-artifact@v7
        with:
          name: PCL.Mac-artifact
          path: ./PCL.Mac-artifact.zip
          archive: false